### ISSUE TITLE
Won't embed SlideShare with 'secret' link

### ISSUE THREAD

**Issue by Babayasin** [w8tcha/CKEditor-oEmbed-Plugin#68]
The case is:

A slideshow at SlideShare; 
private; 
Who can view: People with the secret link;
Allow embeds: Only on domains I choose [domain].

The plugin throws alert saying it cannot get the media.

Embedding the slideshow into the HTML source works.

Changing the privacy to Public makes it work in the plugin as well.

My guess is that /secret/ part of URL confuses the plugin. The fix should be easy.

**Comment by w8tcha** [comment]
The oembed api of slideshare only works with public slideshares. The only solution would be to fall back on direct embed instead of oembed if the slide is private.

Can you post a sample embed code for a private slide embed?

**Comment by Babayasin** [comment]
That's what I did. But SlideShare's "secret" URL is just a bit scrambled, so it should be easy to fix the plugin's parser and add some more functionality.

https://www.slideshare.net/secret/bR1DOYRsKbQjDF

**Comment by w8tcha** [comment]
> so it should be easy to fix the plugin's parser and add some more functionality.

No its not. If it is a private slide, which has embed disabled you can not embed it. This is the case with the url above.

You can try it for yourself by adding the embed code for that slide

```html
<iframe allowfullscreen="" frameborder="0" height="356" marginheight="0" marginwidth="0" scrolling="no" src="https://www.slideshare.net/slideshow/embed_code/43408377" width="427"></iframe>
```

It only shows a Message: "Private content! -  This content has been marked as private by the uploader"

**Comment by Babayasin** [comment]
The slideshow was also limited to a single domain for embedding. Changed it to allow embedding anywhere. Can you please re-check it.

**Comment by w8tcha** [comment]
But it is still impossible to grab the embed code from the link

**Comment by Babayasin** [comment]
Yes, indeed. Sorry for taking your time.
