### ISSUE TITLE
Renders abnormal preview with some Vimeo videos

### ISSUE THREAD

**Issue by geragray** [w8tcha/CKEditor-oEmbed-Plugin#70]
Steps to reproduce:
Go to demo page http://w8tcha.github.io/CKEditor-oEmbed-Plugin/ (or any instance of CKEditor with this plugin). 
Try to paste the following video https://vimeo.com/122969101

Expected: Regular small preview window is shown
Actual: Giant preview window is shown

![screenshot](https://cloud.githubusercontent.com/assets/1540340/6800510/fb9ccaa8-d227-11e4-8634-64e8a178780b.png)

**Comment by voltagectrl** [comment]
+1

**Comment by w8tcha** [comment]
By default it uses the standard dimensions of the video, all you need is change the Resize Type to Responsive Resize or Specific Resize
