### ISSUE TITLE
Yahoo Pipes is going away

### ISSUE THREAD

**Issue by cweagans** [w8tcha/CKEditor-oEmbed-Plugin#76]
http://pipes.yqlblog.net/post/120705592639/pipes-end-of-life-announcement

Looks like this plugin might break as a result, given that YQL is used.

**Comment by cweagans** [comment]
Closed with no comment? There are a lot of sites really depending on this plugin. You just going to ignore the problem?

**Comment by w8tcha** [comment]
This plugin is no longer developed, because there is no an official embed plugin developed by the CKeditor team.  Please migrate to the official CKEditor Embed Plugin - http://ckeditor.com/addon/embed
