### ISSUE TITLE
Twitter / Facebook embedding not rendering

### ISSUE THREAD

**Issue by infojunkie** [w8tcha/CKEditor-oEmbed-Plugin#79]
As stated in the README, Twitter / Facebook embeds (and probably every other embed that includes a script tag) do not render properly. Specifically, the scripts are not run. 

We've done some work to debug this. Even when scripts are made to run using the following code:
```javascript
            jQuery(mediapreview.$).find('script').each(function() {
              if (this.src) {
                var script = jQuery(this).clone();
                jQuery(this).replaceWith(script);
              }
              else {
                var globalEval = function(code, context) {
                  context = context || document;
                  var script = context.createElement("script");
                  
                  script.text = code;
                  context.head.appendChild(script).parentNode.removeChild(script);
                }
                var ck = CKEDITOR.instances['edit-body-und-0-value'],
                    txt = this.text || this.textContent || this.innerHTML || '';
                globalEval(txt, ck.document.$);
              }
            });
```
the embeds don't render. We suspect (but yet haven't proved) that the CKEditor's iframe is confusing those embed scripts.

We'd love to get this solved and are happy to collaborate with project maintainers and community members on this.

**Comment by w8tcha** [comment]
I'm aware of that issue, but i have not found a way to resolve this yet.
