### ISSUE TITLE
Shortened Urls are not working

### ISSUE THREAD

**Issue by shaiksha** [w8tcha/CKEditor-oEmbed-Plugin#81]
I have tried with youtube shortened url in demo of oEmbed. It is not displaying.

Url: https://youtu.be/3u1fu6f8Hto
Url: https://youtu.be/DBXZWB_dNsw
Few Urls resize is not working:
Url: https://vimeo.com/ondemand/tigweldingforthebeginner
Like few urls are not supporting.
Can you fix it and let me know.

**Comment by w8tcha** [comment]
Be aware that this plugin is no longer been developed please migrate to the new embed plugin.

http://ckeditor.com/addon/embed
