### ISSUE TITLE
Does Ckeditor-oEmbed-plugin supports for mobile apps?

### ISSUE THREAD

**Issue by jbalajana** [w8tcha/CKEditor-oEmbed-Plugin#86]
I am using the oEmbed plugin in my website to upload the videos from youtube and vimeo. It is working fine in the webpage. If the same source is copied and pasted it in the mobile app, it is not rendering the video.

This the source code from the ckeditor: 
<div class="embeddedContent oembed-provider- oembed-provider-youtube" data-align="none" data-maxheight="315" data-maxwidth="560" data-oembed="https://www.youtube.com/watch?v=c4DAnQ6DtF8" data-oembed_provider="youtube" data-resizetype="responsive"><iframe allowfullscreen="true" allowscriptaccess="always" frameborder="0" height="315" scrolling="no" src="//www.youtube.com/embed/c4DAnQ6DtF8?wmode=transparent&amp;jqoemcache=XVafe" width="383.5959885386819"></iframe></div>

If I place the same code for the mobile app it is not showing the video. Please let me know the possible solutions.

**Comment by w8tcha** [comment]
Is that still an issue?
