### ISSUE TITLE
Vimeo media ignores resize settings

### ISSUE THREAD

**Issue by StijnVh** [w8tcha/CKEditor-oEmbed-Plugin#90]
Issue #44 is back - Videos from vimeo ignore the size settings. Regardless of settings (no resize/responsive/specific).

The demo at http://w8tcha.github.io/CKEditor-oEmbed-Plugin also suffers from this issue.

Reproduction:
Use the following URL: http://vimeo.com/85217548

**Comment by w8tcha** [comment]
Which browser did you test this? atleast with chrome i still can not reproduce the issue

**Comment by StijnVh** [comment]
I tested using chrome - Retested the demo page and it behaves normally on the first video you insert. If you then afterwards add a 2th video, or alter the properties of the first video, sizing is no longer taken into account (instead the size used the first time is re-used). After a page refresh, sizing is again taken into account (once).

**Comment by w8tcha** [comment]
Should be fixed now. Can you also confirm?

**Comment by StijnVh** [comment]
Used the latest version in my project and indeed resizing issue is fixed. Vimeo videos resize properly according to the given dimensions.
