### ISSUE TITLE
Flickr images no more embeds on https - the scripts blocks the load due Mixed Content. 

### ISSUE THREAD

**Issue by sharadkap** [w8tcha/CKEditor-oEmbed-Plugin#91]
Upon loading any public URL using oEmbed plugin, all the Flickr images are blocked over https.
I see the following issue: 
![screen shot 2018-06-03 at 11 54 03 am](https://user-images.githubusercontent.com/5682531/40882429-fb870e9e-6724-11e8-8f3d-3c0a7ff2ec6f.png)

Any available fix? It is affecting the content on my website. 
Thanks!

**Comment by w8tcha** [comment]
fixed with 

f4739da9e57bc2ff68396c90ea29ad6dbebb82d4
