### ISSUE TITLE
Issue within the CKEditor-oEmbed-Plugin

### ISSUE THREAD

**Issue by crashina** [w8tcha/CKEditor-oEmbed-Plugin#94]
Hi W8tcha, 

I discovered an issue within the oEmbed plugin but I would not like to disclose it here. Is there a way to come in contact with you via your work email? 

My email is john.adamos@redscan.com

Kind Regards,
Ioannis Adamos

**Comment by w8tcha** [comment]
Well you can contact me via thewatcher@watchersnet.de

But i don't understand why you cant post the issue here?

**Comment by crashina** [comment]
Thanks W8tcha, I've sent you an email.
